import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Terms of Service | TemprFit',
  description: 'Terms of Service for TemprFit users and trainers.'
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="container" style={{ padding: '60px 20px', maxWidth: '800px', margin: '0 auto', minHeight: '80vh' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '20px' }}>Terms of Service</h1>
        <p style={{ color: 'var(--color-text-muted)', marginBottom: '40px' }}>Last Updated: October 2026</p>
        
        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>1. Introduction</h2>
          <p style={{ lineHeight: '1.6', color: 'var(--color-text)' }}>
            Welcome to TemprFit. By accessing or using our platform, you agree to be bound by these Terms of Service. TemprFit provides an AI-enhanced fitness platform connecting trainees with personalized workout plans, nutrition guidance, and independent professional trainers.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>2. User Conduct</h2>
          <p style={{ lineHeight: '1.6', color: 'var(--color-text)' }}>
            Users must use the platform respectfully. Any harassment, inappropriate content, or abuse of the AI and community features will result in immediate account termination.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>3. Trainer Revenue & Platform Commission</h2>
          <p style={{ lineHeight: '1.6', color: 'var(--color-text)' }}>
            Independent trainers utilizing the TemprFit marketplace agree to a standard <strong>15% platform commission</strong> on all gross program sales, client subscriptions, and session bookings. This fee covers payment processing, platform hosting, and AI feature maintenance. Net payouts (85%) are processed according to our payout schedule.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '15px' }}>4. Intellectual Property</h2>
          <p style={{ lineHeight: '1.6', color: 'var(--color-text)' }}>
            All original content generated by trainers remains their intellectual property. However, by uploading content to TemprFit, trainers grant us a non-exclusive license to display and distribute this content to their subscribed clients.
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
